# Generated by Django 6.0.2 on 2026-05-17 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_remove_cart_products_cart_created_at_alter_cart_user_and_more"),
        ("order_manager", "0003_order_address_alter_order_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.cart",
            ),
        ),
    ]
